# Generated by Django 5.1.1 on 2024-09-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_rename_item_name_purchase_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='item',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='supplier',
            new_name='supplier_name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='name',
            new_name='supplier_name',
        ),
    ]
