# Generated by Django 5.1.1 on 2024-09-26 11:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_supplier_created_at'),
        ('operation', '0004_alter_purchase_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='supplier_name',
            new_name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='total',
        ),
        migrations.AddField(
            model_name='purchase',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_no',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.item')),
                ('purchase_master_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.purchase')),
            ],
        ),
    ]
