# Generated by Django 5.1.1 on 2024-09-26 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_rename_supplier_name_purchase_supplier_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='purchasedetails',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='purchasedetails',
            old_name='purchase_master_id',
            new_name='purchase_master',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
