# Generated by Django 5.1.1 on 2024-09-27 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_supplier_created_at'),
        ('operation', '0006_rename_supplier_id_purchase_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedetails',
            name='purchase_master',
        ),
        migrations.RenameField(
            model_name='purchasedetails',
            old_name='item',
            new_name='item_id',
        ),
        migrations.CreateModel(
            name='PurchaseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='purchase_master_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='operation.purchasemaster'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
