# Generated by Django 5.1.1 on 2024-09-21 10:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
